### PR TITLE
Step 4, 5

### PR DESCRIPTION
**Pull request by Csaba8472**
This PR implements Step 5 and also Step 4(if you remove KMM from Step 5 you get Step 4).

```
Step 4
Because Xamarin will reach end of support at some point ([2 years after final release](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin)) also test building of a native Obj-C/Swift watchOS app and a native Java/Kotlin Wear OS app bundlded within the MAUI project created in step 3.

Step 5
Implement both wearable apps with [Kotlin Multiplatform Mobile](https://kotlinlang.org/lp/mobile/) to keep a single logic base.
```

**Wear OS app**
Relatively easy, as in play console you distribute it as a separate apk. To be able to use shared code from the KMM "shared" library this is the only thing you need to add: `implementation(project(":shared"))` to gradle.

**WatchOS app**
This is more complicated. To set up KMM you need to create a new KMM project with "Regular framework" iOS framework distribution. Then follow [this guide](https://kotlinlang.org/docs/multiplatform-mobile-understand-project-structure.html#ios-application) to setup the WatchOS app's shared framework.

With [this modification](https://github.com/xamarin/xamarin-macios/issues/10070#issuecomment-1160444300) you can include the watch app in the iOS app, which means when you run your iOS app from VSMac, it doesn't delete the watch app but it installs the latest. Watch app and iOS app can be debugged at the same time, in that case you need to install the watch app with "Supports running without ios app installation" set to true. Also make sure WatchAppConfiguration is properly set for `watchos` if you run your app on device and `watchsimulator` if you run your app in emulator.

I couldn't release with similar changes above, because dsyms hasn't been copied, and apple complained about missing bitcode. However, the [copy-paste method](https://github.com/xamarin/xamarin-macios/issues/10070#issuecomment-727083181) works well for me.

Screenshot 2022-06-25 at 21 04 44

### CODE REVIEW

**Comment by beeradmoore** [comment]
This is a great PR and most probably the hardest part of this repo. Thanks for sending it through.

I have a few questions about what is going on with this:
1. In Step25KMM project is it necessary to have the iOS and Android app projects for the KMM wearable stuff to work? Would cut out a lot of fluff if it wasn't needed.
2. I'm not familiar with native iOS/wearable projects but I think there may be built files added to this PR. I am unsure if DerivedData is what gets built by the project (sort of like bin and obj folders for MAUI and Xamarin.Forms projects). If so can we remove these so it isn't 14,000 files changed?
3. With the data being built in step 2, is it possible to build that via command line so then we can add that to a script to simplify things?

**Comment by Csaba8472** [comment]
Thank you, I have a MAUI app with watchos and wearos companion apps, I've spent a lot of time figuring out these things, also community helped a lot.

1. The androidApp is not necessary, I've removed it. The iosApp xcode project is necessary because that has the companion watchos project.
2. You're correct, most of the DerivedData stuff is unnecessary I've removed those. Only the Products folder is needed because it has the watchos app.
3. What data do you mean?

**Comment by beeradmoore** [comment]
(whops I read GitHub wrong. That wasn't 14,000 files, it was 14,000 lines. But was still things that weren't meant to be added)

For the data for point 3 I was referring to the DerivedData from point 2. I don't think the Products folder is needed, but can be built on a users own machine by running a built script (which we could later add into the csproj as a build step possibly).

Ideally you don't put any compiled or temporary data into the git repo if it gets built by the users machine.


Slight side note (random ramblings incomming): Looking into the watchOS stuff is interesting. Android app is not required because you can submit the WearOS app as an independent app even if it is not independent. This [might be possible](https://developer.apple.com/documentation/watchos-apps/creating-independent-watchos-apps) with watchOS if you are targeting watchOS 6 and higher. So you would build native watchOS app as a standalone but make it a companion app and submit it independently.

**Comment by Csaba8472** [comment]
```
For the data for point 3 I was referring to the DerivedData from point 2. I don't think the Products folder is needed, but can be built on a users own machine by running a built script (which we could later add into the csproj as a build step possibly).

Ideally you don't put any compiled or temporary data into the git repo if it gets built by the users machine.
```
I agree, I left there just to have it as an example. In xcode, you can set DerivedData folder path as default, relative(to the project) and custom. What I did works only if DerivedData folder path is relative to the project. 

```
Slight side note (random ramblings incomming): Looking into the watchOS stuff is interesting. Android app is not required because you can submit the WearOS app as an independent app even if it is not independent. This [might be possible](https://developer.apple.com/documentation/watchos-apps/creating-independent-watchos-apps) with watchOS if you are targeting watchOS 6 and higher. So you would build native watchOS app as a standalone but make it a companion app and submit it independently.
```
Yes, wearos apk should be uploaded separately, and whether it's independent or not should be marked in [manifest](https://developer.android.com/training/wearables/packaging#specifying-app-as-standalone). 

You can create standalone watchos apps in two ways:
1. with an iOS app (setting "Supports running without ios app installation" to true)
2. without an iOS app. 

In both cases your xcode project will have the iOS part(in 2. case it'll be only a stub) and you can upload only one build which has your ios app or ios+watch app or only watch app.

**Comment by beeradmoore** [comment]
Thanks again for these contributions @Csaba8472

**Pull request merged**
